name: Publish to Thunderstore

on: 
  release:
    types: [published]

env:
  name: ShowTotalLoot
  # Dependencies + Deps Versions
  menulib: 2.3.0 

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Use checkout to publish the files in your repo
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4.3.1
        with: 
          dotnet-version: '9.0.x'

      - name: Download Thunderstore Dependencies
        run: |
          mkdir -p Dependencies

          wget https://thunderstore.io/package/download/nickklmao/MenuLib/${{env.menulib}}/ -O menulib.zip
          unzip menulib.zip -d dep_extracted

          find dep_extracted -name "*.dll" -exec cp {} Dependencies/ \;
    
      - name: Build the mod
        run: dotnet build . -c Release

      - name: Prepare package directory
        run: |
          mkdir -p package
          cp README.md icon.png package/
          cp ./bin/Release/netstandard2.1/${{ env.name }}.dll package/

      - uses: GreenTF/upload-thunderstore-package@87a940b1f508ab1a6866eded55a9539afdf09792
        with:
          # the thunderstore 'team' to publish under
          namespace: itsageba 
          # Description of Mod 
          description: A simple mod that shows the total loot a player can collect from the level on their HUD. 
          token: ${{ secrets.THUNDERSTORE_KEY }}
          # the name of the package
          name: ${{ env.name }} 
          version: ${{ github.ref_name }} # Use the tag as the package version
          community: repo
          # A list, separated by spaces
          deps: BepInEx-BepInExPack@5.4.2100 nickklmao-MenuLib@${{env.menulib}}
          #A list, separated by newline characters
          categories: |
            clientside
            mods
            misc
          path: ./package